### ISSUE TITLE
Type Error and EOF Error while runnung demo programs

### ISSUE THREAD

**Issue by muzzahmed** [microsoft/pybryt#179]
**Describe the bug**
Getting EOF error while running the demo programs

**To Reproduce**
Execute demo programs in jupyter Notebook

**Expected behavior**
Program to run

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser :chrome
EOFError                                  Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_9880\1693718465.py in <module>
      2 for subm in subms:
      3     nb = nbformat.read(subm, as_version=4)
----> 4     student_impls.append(pybryt.StudentImplementation(nb))
      5 
      6 student_impls

c:\users\akshay\appdata\local\programs\python\python37\lib\site-packages\pybryt\student.py in _init_(self, path_or_nb, addl_filenames, output, timeout)
     65             raise TypeError(f"path_or_nb is of unsupported type {type(path_or_nb)}")
     66 
---> 67         self._execute(timeout, addl_filenames=addl_filenames, output=output)
     68 
     69     def _execute(

c:\users\akshay\appdata\local\programs\python\python37\lib\site-packages\pybryt\student.py in _execute(self, timeout, addl_filenames, output)
     87             self.nb_path,
     88             addl_filenames=addl_filenames,
---> 89             timeout=timeout,
     90         )
     91 

c:\users\akshay\appdata\local\programs\python\python37\lib\site-packages\pybryt\execution\_init_.py in execute_notebook(nb, nb_path, addl_filenames, timeout)
     99 
    100     with open(footprint_fp, "rb") as f:
--> 101         footprint: MemoryFootprint = dill.load(f)
    102 
    103     os.remove(footprint_fp)

c:\users\akshay\appdata\local\programs\python\python37\lib\site-packages\dill\_dill.py in load(file, ignore, **kwds)
    311     See :func:`loads` for keyword arguments.
    312     """
--> 313     return Unpickler(file, ignore=ignore, **kwds).load()
    314 
    315 def loads(str, ignore=None, **kwds):

c:\users\akshay\appdata\local\programs\python\python37\lib\site-packages\dill\_dill.py in load(self)
    523 
    524     def load(self): #NOTE: if settings change, need to update attributes
--> 525         obj = StockUnpickler.load(self)
    526         if type(obj)._module_ == getattr(main_module, 'name', 'main_'):
    527             if not self._ignore:

EOFError: Ran out of input

**Comment by leestott** [comment]
unable to repo this error please ensure you have the latest install of pybryt
