### ISSUE TITLE
Relative tolerance

### ISSUE THREAD

**Issue by marijanbeg** [microsoft/pybryt#37]
Tolerances allow student's values to deviate from the reference ones. Having the ability to define only the absolute tolerance poses several difficulties:

- It is required for the teacher to inspect each output value separately and decide what is an acceptable tolerance.
- Values such as lists, tuples, arrays, can contain values with different orders of magnitude and specifying a single absolute tolerance value is not sufficient.

Having the ability to define relative tolerance would help to resolve those difficulties and bring the comparison of values closer to `numpy.allclose` (https://numpy.org/doc/stable/reference/generated/numpy.allclose.html).

**Comment by chrispyles** [comment]
This is implemented in #37 and will be included in the next release of PyBryt.

**Comment by marijanbeg** [comment]
Thanks, @chrispyles!
