### ISSUE TITLE
Comparison with reference implementation from within a notebook

### ISSUE THREAD

**Issue by marijanbeg** [microsoft/pybryt#39]
For PyBryt tests (comparison with reference implementation) to be executed, it is necessary for the student to commit and push their solution to a repository. Most (beginner) programming and data science courses do not expect students to be familiar with version control. It would be convenient for a student to be able to run tests and get feedback right after they implement their solution. For instance,

- Teacher can write a "testing cell" right after the cell where a student writes their solution (similar to the usual `assert solution == 5` cell) to compare the student's solution to the reference one.
- This way, student would get quick feedback in the same notebook without having to push their solution and waiting for CI to run and provide feedback.
- For multiple attempts, this would substantially reduce the time student spends working on an exercise.

**Comment by leestott** [comment]
@marijanbeg so students do not have to do any commits to repos to have PyBryt run within a notebook environment.  If you download the demos Median and Goldbach and simply run these they all work locally.. https://github.com/microsoft/pybryt/tree/main/demo

**Comment by chrispyles** [comment]
Going to close this issue in favor of #38, since offline running is implemented and the new features described there can also be used to implement this request.
