### ISSUE TITLE
PyBryt CLI Feature

### ISSUE THREAD

**Issue by leestott** [microsoft/pybryt#44]
PyBryt CLI 

Goal : The ability to use a command line interface to create a reference implementation and grade a students work.

**Describe the solution you'd like**
Goal here is to allow the easy onboarding of educators to using PyBryt 

So task would be 
1. Educator can create a reference implementation 
2. Educator uses PyBryt CLI to create a solution with reference implementations 

**Describe alternatives you've considered**
CLI Features bases MVP
- CLI to run a student code based on reference implementation (single submission)
Future features
- Pickle Reference implementation 
- Use Pickle reference to undertake assessment 
- Or CLI to pickle and compare 
 
**Additional context**
To be discussed.

**Comment by chrispyles** [comment]
Additional CLI features:

- [ ] Create a series of memory footprints (in parallel)
- [ ] check output as a report a la the `check` context manager -- printed to console or to text file?
