### ISSUE TITLE
Checking variable value within the check context

### ISSUE THREAD

**Issue by marijanbeg** [microsoft/pybryt#61]
**Describe the bug**
We want the student to perform some computations in a notebook cell and store the answer in a variable. In the next cell, we want to check the value of that variable using PyBryt. We write:

```python
with pybryt.check(...):
    # variable or operations on a variable
```

We expect that everything stored in memory within the context will be available to PyBryt for validation. However, we are not able to access the variable value unless we write a workaround function.

**To Reproduce**
We demonstrate the error in `02-code-outside-functions` example in https://github.com/marijanbeg/pybryt-examples.

**Expected behavior**
We expect the behaviour similar to:
```python
with pybryt.check(...):
    student_variable # or
    # tmpvar = student_variable
```
to expose the value of the variable to PyBryt.

**Comment by chrispyles** [comment]
@marijanbeg I've opened #87 which implements a fix for this issue. Once this is merged, any of the implementations in the notebook you provided should work, including just accessing the variable:

```python
with pybryt.check(...):
	student_var
```
