### ISSUE TITLE
Annotation for requiring/forbidding the use of specific functions

### ISSUE THREAD

**Issue by chrispyles** [microsoft/pybryt#85]
Instructors should be able to write annotations for asserting the use or non-use of specific functions.

This change is somewhat complicated, as it will involve editing the trace function to track information that it is not currently tracking (which function is being traced and to what package it belongs, namely).

**Comment by ranigb** [comment]
This one may be relevant:
https://docs.python.org/3/library/trace.html

**Comment by chrispyles** [comment]
I think we decided to resolve this issue by instead tracking function calls and letting the instructor use some post-grading process to assert conditions on this information.

#92 implements this feature by updating the tracing function and exposes the list of calls as `(filename, function name)` tuples in `StudentImplementation.calls`.
